# -*- coding: utf-8 -*-
"""Build dist/fonts/*.woff2 (subset CJK) + dist/fonts.css (@font-face refs).

Fonts are NOT base64-embedded into the HTML. The dashboard links the external
.woff2 files via fonts.css so the generated HTML stays small (a few hundred KB
instead of ~7.7MB). Run this whenever the source fonts change.
"""
import io
import re
from pathlib import Path
from fontTools.subset import Subsetter, Options
from fontTools.ttLib import TTFont

BASE = Path(__file__).resolve().parent
DIST = BASE / "dist"
FONT_DIR = DIST / "fonts"
FONT_DIR.mkdir(parents=True, exist_ok=True)
OUT_CSS = DIST / "fonts.css"

# 旧的 base64 内嵌产物，已废弃
OLD_CSS = BASE / "fonts_embed.css"

# 全部为 SIL OFL 授权字体，允许子集化与再分发：
#   ZCOOL XiaoWei  — 中文展示（优雅宋体感，单一 Regular）
#   Space Grotesk  — 拉丁/数字展示（科技感，可变字体 300–700）
#   Poppins        — 拉丁正文（已用）
FONTS = [
    {
        "family": "ZCOOL XiaoWei",
        "src": r"T:\BaiduSyncdisk\_开源字体\「筛选后的字体」\ZCOOLXiaoWei-Regular.ttf",
        "weight": "400", "style": "normal", "subset_cjk": True,
    },
    {
        "family": "Space Grotesk",
        "src": r"T:\BaiduSyncdisk\_开源字体\「筛选后的字体」\SpaceGrotesk-VF.ttf",
        "weight": "300 700", "style": "normal", "subset_cjk": False, "variable": True,
    },
    {
        "family": "Poppins",
        "src": r"T:\BaiduSyncdisk\_开源字体\「筛选后的字体」\Poppins-Regular.ttf",
        "weight": "400", "style": "normal", "subset_cjk": False,
    },
]


def slug(f):
    fam = re.sub(r"[^a-zA-Z0-9]", "", f["family"])
    return f"{fam}-{f['weight'].replace(' ', '')}-{f['style']}"


def gb2312_chars():
    """All chars decodable from GB2312 double-byte range (~7400 incl. 6763 CJK)."""
    chars = []
    for hi in range(0xA1, 0xF8):
        for lo in range(0xA1, 0xFF):
            try:
                s = bytes([hi, lo]).decode("gb2312")
                if len(s) == 1:
                    chars.append(s)
            except (UnicodeDecodeError, ValueError):
                pass
    return chars


def build_charset(cjk: bool):
    chars = set()
    chars.update(chr(c) for c in range(0x20, 0x7F))
    chars.update("「」『』、。—《》？【】！…·～％‰′″℃℉±×÷≈≠≤≥→←↑↓①②③④⑤⑥⑦⑧⑨⑩ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩ")
    chars.update("€™‘’“”–—…•")
    if cjk:
        chars.update(gb2312_chars())
    return "".join(sorted(chars))


def subset_woff2(src_path: str, cjk: bool) -> bytes:
    font = TTFont(src_path)
    opts = Options()
    opts.flavor = "woff2"
    opts.desubroutinize = True
    opts.drop_tables += ["GSUB", "GPOS", "GDEF"] if not cjk else []
    opts.name_IDs = ["*"]
    opts.notdef_outline = True
    opts.recalc_bounds = True
    opts.instancer = False

    subsetter = Subsetter(options=opts)
    text = build_charset(cjk)
    subsetter.populate(text=text)
    subsetter.subset(font)

    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


def main():
    blocks = []
    total_raw = total_out = 0
    for f in FONTS:
        src = Path(f["src"])
        raw_size = src.stat().st_size
        data = subset_woff2(str(src), f["subset_cjk"])
        s = slug(f)
        woff2_path = FONT_DIR / f"{s}.woff2"
        woff2_path.write_bytes(data)
        # 相对路径：fonts.css 在 dist/，woff2 在 dist/fonts/，故 url(fonts/xxx.woff2)
        blocks.append(
            f"@font-face {{\n"
            f"  font-family: '{f['family']}';\n"
            f"  src: url(fonts/{s}.woff2) format('woff2');\n"
            f"  font-weight: {f['weight']};\n"
            f"  font-style: {f['style']};\n"
            f"  font-display: swap;\n"
            f"}}"
        )
        total_raw += raw_size
        total_out += len(data)
        print(f"{f['family']:14s} w{f['weight']:8s} {f['style']:6s} "
              f"{raw_size/1048576:7.2f}MB -> {len(data)/1048576:5.2f}MB  ({s}.woff2)")

    css = "/* Auto-generated by build_fonts_css.py - do not edit */\n" + "\n\n".join(blocks)
    OUT_CSS.write_text(css, encoding="utf-8")

    # 清理旧的内嵌产物
    if OLD_CSS.exists():
        OLD_CSS.unlink()
        print(f"removed legacy: {OLD_CSS.name}")

    print(f"\nTOTAL: {total_raw/1048576:.1f}MB raw -> {total_out/1048576:.1f}MB woff2")
    print(f"OUT css  -> {OUT_CSS}")
    print(f"OUT fonts-> {FONT_DIR}")


if __name__ == "__main__":
    main()
